export const carCategories = [
	"Sedan",
	"SUV",
	"Coupe",
	"Hatchback",
	"Convertible",
	"Wagon",
	"Pickup Truck",
	"Minivan",
	"Crossover",
	"Electric Vehicle",
	"Hybrid Vehicle",
	"Luxury Vehicle",
	"Sports Car",
	"Off-Road Vehicle",
	"Compact Car",
	"Full-Size Car",
	"Mid-Size Car",
	"Subcompact Car",
	"Supermini",
	"Microcar",
];
